name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: linux

    steps:
    - uses: actions/checkout@v2    
    - name: Cake Action
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: Test
