name: Push NuGet package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Cake Action
      uses: cake-build/cake-action@v1.4.0
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_API_URL: ${{ secrets.NUGET_API_URL }}
      with:
        target: NuGetPush
